### PR TITLE
Minor ConcurrencyLimiter tweaks

### PR DESCRIPTION
**Pull request by liljencrantz**
- Use ArrayBlockingQueue, which has more suitable semantics
- Add interface
- Track remaining capacity, not used capacity, since the
  former is more useful for monitoring purposes.

### CODE REVIEW

**Comment by liljencrantz** [comment]
@krka @spkrka

**Comment by liljencrantz** [comment]
Coverage decreases as a result of this patch set, but only because the line count increases. Test coverage for the affected class remains stead at 100 %.

**Comment by spkrka** [comment]
Looks good. It breaks compatibility so maybe it we should update pom.xml to reflect that. Annoying to bump major version though.

Perhaps we can rename the interface, keep the old class and make it implement the interface and mark the bad methods as `@Deprecated`.

The new interface could be called `FutureJobDeferrer` or something that is less coupled to the implementation details.

**Comment by liljencrantz** [comment]
Regarding naming, another option is AsyncSemaphore.

Regarding backwards compat, deprecation, etc., I doubt anyone uses ConcurencyLimiter yet, so a break might be OK if we do it soon. In the end, this is your call, you own the project. If you want me to rename things, re-add the old methods with @Deprecated or whatever, let me know and I can do it. I can see reasons for and against and don't feel emotionally invested in either outcome. :-)

**Comment by caesar-ralf** [comment]
closing old PR that has not been reviewed/merged in years. Feel free to re-open if you believe it's still relevant

**Pull request closed without merging**
